// Generated by gencpp from file kusv_msgs/PolyfitLaneDataArray.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_POLYFITLANEDATAARRAY_H
#define KUSV_MSGS_MESSAGE_POLYFITLANEDATAARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kusv_msgs/PolyfitLaneData.h>

namespace kusv_msgs
{
template <class ContainerAllocator>
struct PolyfitLaneDataArray_
{
  typedef PolyfitLaneDataArray_<ContainerAllocator> Type;

  PolyfitLaneDataArray_()
    : polyfitLanes()  {
    }
  PolyfitLaneDataArray_(const ContainerAllocator& _alloc)
    : polyfitLanes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >::other >  _polyfitLanes_type;
  _polyfitLanes_type polyfitLanes;





  typedef boost::shared_ptr< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> const> ConstPtr;

}; // struct PolyfitLaneDataArray_

typedef ::kusv_msgs::PolyfitLaneDataArray_<std::allocator<void> > PolyfitLaneDataArray;

typedef boost::shared_ptr< ::kusv_msgs::PolyfitLaneDataArray > PolyfitLaneDataArrayPtr;
typedef boost::shared_ptr< ::kusv_msgs::PolyfitLaneDataArray const> PolyfitLaneDataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'kusv_msgs': ['/home/lke/ACL_KUSV/src/msgs/kusv_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/kinetic/share/pcl_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'jsk_footstep_msgs': ['/opt/ros/kinetic/share/jsk_footstep_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'jsk_recognition_msgs': ['/opt/ros/kinetic/share/jsk_recognition_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f73b0014879f8495deb3d40eb300c75a";
  }

  static const char* value(const ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf73b0014879f8495ULL;
  static const uint64_t static_value2 = 0xdeb3d40eb300c75aULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/PolyfitLaneDataArray";
  }

  static const char* value(const ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PolyfitLaneData[] polyfitLanes\n\
\n\
================================================================================\n\
MSG: kusv_msgs/PolyfitLaneData\n\
float64 a\n\
float64 b\n\
float64 c\n\
float64 d\n\
";
  }

  static const char* value(const ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.polyfitLanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolyfitLaneDataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::PolyfitLaneDataArray_<ContainerAllocator>& v)
  {
    s << indent << "polyfitLanes[]" << std::endl;
    for (size_t i = 0; i < v.polyfitLanes.size(); ++i)
    {
      s << indent << "  polyfitLanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >::stream(s, indent + "    ", v.polyfitLanes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_POLYFITLANEDATAARRAY_H
