// Generated by gencpp from file kusv_msgs/PolyfitLaneData.msg
// DO NOT EDIT!


#ifndef KUSV_MSGS_MESSAGE_POLYFITLANEDATA_H
#define KUSV_MSGS_MESSAGE_POLYFITLANEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kusv_msgs
{
template <class ContainerAllocator>
struct PolyfitLaneData_
{
  typedef PolyfitLaneData_<ContainerAllocator> Type;

  PolyfitLaneData_()
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)  {
    }
  PolyfitLaneData_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> const> ConstPtr;

}; // struct PolyfitLaneData_

typedef ::kusv_msgs::PolyfitLaneData_<std::allocator<void> > PolyfitLaneData;

typedef boost::shared_ptr< ::kusv_msgs::PolyfitLaneData > PolyfitLaneDataPtr;
typedef boost::shared_ptr< ::kusv_msgs::PolyfitLaneData const> PolyfitLaneDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kusv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kusv_msgs': ['/home/lke/ACL_KUSV/src/msgs/kusv_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/kinetic/share/pcl_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'jsk_footstep_msgs': ['/opt/ros/kinetic/share/jsk_footstep_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'jsk_recognition_msgs': ['/opt/ros/kinetic/share/jsk_recognition_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5c1b8d0c23e6e29f5d8d9fbdb957dac";
  }

  static const char* value(const ::kusv_msgs::PolyfitLaneData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5c1b8d0c23e6e29ULL;
  static const uint64_t static_value2 = 0xf5d8d9fbdb957dacULL;
};

template<class ContainerAllocator>
struct DataType< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kusv_msgs/PolyfitLaneData";
  }

  static const char* value(const ::kusv_msgs::PolyfitLaneData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n\
float64 b\n\
float64 c\n\
float64 d\n\
";
  }

  static const char* value(const ::kusv_msgs::PolyfitLaneData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolyfitLaneData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kusv_msgs::PolyfitLaneData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kusv_msgs::PolyfitLaneData_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUSV_MSGS_MESSAGE_POLYFITLANEDATA_H
