(cl:defpackage kusv_msgs-msg
  (:use )
  (:export
   "<CONTROLCMD>"
   "CONTROLCMD"
   "<DETECTEDOBJECT>"
   "DETECTEDOBJECT"
   "<LANEPOINTDATA>"
   "LANEPOINTDATA"
   "<POLYFITLANEDATA>"
   "POLYFITLANEDATA"
   "<POLYFITLANEDATAARRAY>"
   "POLYFITLANEDATAARRAY"
   "<WAYPOINT>"
   "WAYPOINT"
   "<WAYPOINTARRAY>"
   "WAYPOINTARRAY"
   "<KUSV_CANINFO>"
   "KUSV_CANINFO"
  ))

