(cl:defpackage kusv_msgs-msg
  (:use )
  (:export
   "<DETECTEDOBJECT>"
   "DETECTEDOBJECT"
   "<DETECTEDOBJECTARRAY>"
   "DETECTEDOBJECTARRAY"
   "<LANEPOINTDATA>"
   "LANEPOINTDATA"
   "<LANEPOINTDATAARRAY>"
   "LANEPOINTDATAARRAY"
   "<POLYFITLANEDATA>"
   "POLYFITLANEDATA"
   "<POLYFITLANEDATAARRAY>"
   "POLYFITLANEDATAARRAY"
   "<WAYPOINT>"
   "WAYPOINT"
   "<WAYPOINTARRAY>"
   "WAYPOINTARRAY"
   "<KUSV_CANINFO>"
   "KUSV_CANINFO"
   "<KUSV_GLOBALPOSE>"
   "KUSV_GLOBALPOSE"
  ))

